package fermyon:spin-test@2.0.0;

interface test-types {
    variant error {
        other(string),
    }
}

interface spin-test-handler {
    use test-types.{error};
    get-test-list: func() -> result<list<string>, error>;
    execute-test: func(name: string) -> result<_, error>;
}

world spin-test {
    export spin-test-handler;
}